name: CI / CD

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃 코드
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # 전체 히스토리 가져오기

      - name: Kakao 키 삽입
        run: |
          sed -i "s/YOUR_APP_KEY/${{ secrets.KAKAO_JS_KEY }}/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAGES_PAT }}     # PAT 사용
          publish_branch: gh-pages
          publish_dir: ./
